// common
export const SHOW_LOADING = 'SHOW_LOADING'

// tron-web
export const GET_TRON_WEB_INSTANCE = 'GET_TRON_WEB_INSTANCE'
export const GET_FACTORY_INSTANCE = 'GET_FACTORY_INSTANCE'
export const GET_DEPLOYED_CONTRACT = 'GET_DEPLOYED_CONTRACT'
export const SET_CURRENT_CONTRACT = 'SET_CURRENT_CONTRACT'